# Generated by Django 4.2.7 on 2025-12-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semesters',
            field=models.ManyToManyField(blank=True, to='core.semester', verbose_name='سمسترها'),
        ),
    ]
