# Generated by Django 4.2.7 on 2025-12-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.semester', verbose_name='سمستر'),
        ),
    ]
