# Generated by Codex on 2026-02-05

from django.db import migrations, models
import django.db.models.deletion


def create_reference_data(apps, schema_editor):
    StudyLevel = apps.get_model('core', 'StudyLevel')
    CoursePeriod = apps.get_model('core', 'CoursePeriod')
    Semester = apps.get_model('core', 'Semester')

    levels = [
        ('aali', 'عالی'),
        ('moteseta', 'متوسطه'),
        ('ebtedai', 'ابتداییه'),
    ]

    for code, name in levels:
        obj, _ = StudyLevel.objects.get_or_create(code=code, defaults={'name': name})
        if obj.name != name:
            obj.name = name
            obj.save(update_fields=['name'])

    for n in range(1, 5):
        Semester.objects.get_or_create(number=n)

    for n in range(1, 7):
        CoursePeriod.objects.get_or_create(number=n)


def _column_exists(schema_editor, table, column):
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    if vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info('{table}')")
        return column in [row[1] for row in cursor.fetchall()]
    try:
        desc = schema_editor.connection.introspection.get_table_description(cursor, table)
        return column in [c.name for c in desc]
    except Exception:
        return False


def add_student_level_column(apps, schema_editor):
    if _column_exists(schema_editor, 'core_student', 'level_id'):
        return
    schema_editor.execute('ALTER TABLE "core_student" ADD COLUMN "level_id" bigint NULL')


def add_student_grade12_column(apps, schema_editor):
    if _column_exists(schema_editor, 'core_student', 'is_grade12_graduate'):
        return
    schema_editor.execute('ALTER TABLE "core_student" ADD COLUMN "is_grade12_graduate" bool NOT NULL DEFAULT 0')


def create_m2m_table_if_missing(schema_editor, table, left_col, right_col):
    existing = schema_editor.connection.introspection.table_names()
    if table in existing:
        return
    schema_editor.execute(
        f'CREATE TABLE "{table}" ('
        '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
        f'"{left_col}" bigint NOT NULL, '
        f'"{right_col}" bigint NOT NULL'
        ')'
    )
    schema_editor.execute(
        f'CREATE UNIQUE INDEX "{table}_{left_col}_{right_col}_uniq" '
        f'ON "{table}" ("{left_col}", "{right_col}")'
    )
    schema_editor.execute(
        f'CREATE INDEX "{table}_{left_col}" ON "{table}" ("{left_col}")'
    )
    schema_editor.execute(
        f'CREATE INDEX "{table}_{right_col}" ON "{table}" ("{right_col}")'
    )


def create_student_periods_m2m(apps, schema_editor):
    create_m2m_table_if_missing(schema_editor, 'core_student_periods', 'student_id', 'courseperiod_id')


def create_teacher_levels_m2m(apps, schema_editor):
    create_m2m_table_if_missing(schema_editor, 'core_teacher_levels', 'teacher_id', 'studylevel_id')


def create_teacher_periods_m2m(apps, schema_editor):
    create_m2m_table_if_missing(schema_editor, 'core_teacher_periods', 'teacher_id', 'courseperiod_id')


def create_models_if_missing(apps, schema_editor):
    """Create StudyLevel and CoursePeriod tables only if they don't exist."""
    existing = schema_editor.connection.introspection.table_names()
    vendor = schema_editor.connection.vendor

    def exec_sql(sql):
        schema_editor.execute(sql)

    if vendor == 'sqlite':
        if 'core_studylevel' not in existing:
            exec_sql(
                'CREATE TABLE IF NOT EXISTS "core_studylevel" '
                '("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
                '"code" varchar(20) NOT NULL UNIQUE, '
                '"name" varchar(50) NOT NULL UNIQUE)'
            )
        if 'core_courseperiod' not in existing:
            exec_sql(
                'CREATE TABLE IF NOT EXISTS "core_courseperiod" '
                '("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
                '"number" smallint NOT NULL UNIQUE)'
            )
        return

    if vendor == 'postgresql':
        if 'core_studylevel' not in existing:
            exec_sql(
                'CREATE TABLE IF NOT EXISTS "core_studylevel" '
                '("id" bigserial PRIMARY KEY, '
                '"code" varchar(20) NOT NULL UNIQUE, '
                '"name" varchar(50) NOT NULL UNIQUE)'
            )
        if 'core_courseperiod' not in existing:
            exec_sql(
                'CREATE TABLE IF NOT EXISTS "core_courseperiod" '
                '("id" bigserial PRIMARY KEY, '
                '"number" smallint NOT NULL UNIQUE)'
            )
        return

    if vendor == 'mysql':
        if 'core_studylevel' not in existing:
            exec_sql(
                'CREATE TABLE IF NOT EXISTS `core_studylevel` '
                '(`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, '
                '`code` varchar(20) NOT NULL UNIQUE, '
                '`name` varchar(50) NOT NULL UNIQUE)'
            )
        if 'core_courseperiod' not in existing:
            exec_sql(
                'CREATE TABLE IF NOT EXISTS `core_courseperiod` '
                '(`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, '
                '`number` smallint NOT NULL UNIQUE)'
            )
        return

    # Generic fallback
    if 'core_studylevel' not in existing:
        exec_sql(
            'CREATE TABLE IF NOT EXISTS "core_studylevel" '
            '("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
            '"code" varchar(20) NOT NULL UNIQUE, '
            '"name" varchar(50) NOT NULL UNIQUE)'
        )
    if 'core_courseperiod' not in existing:
        exec_sql(
            'CREATE TABLE IF NOT EXISTS "core_courseperiod" '
            '("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
            '"number" smallint NOT NULL UNIQUE)'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_migrate_class_name_to_foreign_key'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_models_if_missing, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CoursePeriod',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='شماره دوره')),
                    ],
                    options={
                        'verbose_name': 'دوره',
                        'verbose_name_plural': 'دوره\u200cها',
                    },
                ),
                migrations.CreateModel(
                    name='StudyLevel',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=20, unique=True, verbose_name='کد سطح')),
                        ('name', models.CharField(max_length=50, unique=True, verbose_name='نام سطح')),
                    ],
                    options={
                        'verbose_name': 'سطح آموزشی',
                        'verbose_name_plural': 'سطوح آموزشی',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_student_level_column, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='level',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studylevel', verbose_name='سطح آموزشی'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_student_grade12_column, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='is_grade12_graduate',
                    field=models.BooleanField(default=False, verbose_name='فارغ صنف دوازدهم'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_student_periods_m2m, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='periods',
                    field=models.ManyToManyField(blank=True, to='core.courseperiod', verbose_name='دوره\u200cها'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_teacher_levels_m2m, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='teacher',
                    name='levels',
                    field=models.ManyToManyField(blank=True, to='core.studylevel', verbose_name='سطوح تدریس'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_teacher_periods_m2m, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='teacher',
                    name='periods',
                    field=models.ManyToManyField(blank=True, to='core.courseperiod', verbose_name='دوره\u200cها'),
                ),
            ],
        ),
        migrations.RunPython(create_reference_data, reverse_code=migrations.RunPython.noop),
    ]
