# Generated by Codex on 2026-02-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('core', '0017_teacher_contract'),
	]

	operations = [
		migrations.CreateModel(
			name='StudentBehavior',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('entry_type', models.CharField(choices=[('violation', 'تخلف'), ('merit', 'امتیاز')], max_length=10, verbose_name='نوع ثبت')),
				('note', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
				('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
				('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_entries', to='core.student')),
			],
			options={
				'verbose_name': 'تخلف/امتیاز دانش‌آموز',
				'verbose_name_plural': 'تخلفات/امتیازات دانش‌آموزان',
			},
		),
		migrations.CreateModel(
			name='TeacherBehavior',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('entry_type', models.CharField(choices=[('violation', 'تخلف'), ('merit', 'امتیاز')], max_length=10, verbose_name='نوع ثبت')),
				('note', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
				('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
				('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_entries', to='core.teacher')),
			],
			options={
				'verbose_name': 'تخلف/امتیاز استاد',
				'verbose_name_plural': 'تخلفات/امتیازات اساتید',
			},
		),
	]
