# Generated by Django 4.2.7 on 2026-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_teacher_plan_file_student_plan_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='plan_file',
        ),
        migrations.AddField(
            model_name='teacher',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_plans/', verbose_name='پلان درسی'),
        ),
    ]
