# Generated by Django 4.2.7 on 2026-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_student_plan_file_teacher_plan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='student_certificates/', verbose_name='شهادت\u200cنامه'),
        ),
    ]
