# Generated by Django 4.2.7 on 2026-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_student_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False, verbose_name='فارغ'),
        ),
    ]
