from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('logo.jpg', views.logo, name='logo'),
    path('emirate.png', views.emirate_logo, name='emirate_logo'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('students/new/', views.student_create, name='student_create'),
    path('students/<int:pk>/edit/', views.student_edit, name='student_edit'),
    path('students/<int:pk>/delete/', views.student_delete, name='student_delete'),
    path('students/behavior/add/', views.student_behavior_add, name='student_behavior_add'),
    path('students/behavior/<int:pk>/update/', views.student_behavior_update, name='student_behavior_update'),
    path('students/behavior/<int:pk>/delete/', views.student_behavior_delete, name='student_behavior_delete'),
    path('students/<int:pk>/appreciation/', views.student_appreciation_print, name='student_appreciation_print'),
    path('', views.student_list, name='student_list'),
    path('classes/new/', views.class_create, name='class_create'),
    path('classes/<int:pk>/edit/', views.class_edit, name='class_edit'),
    path('classes/<int:pk>/delete/', views.class_delete, name='class_delete'),
    path('classes/', views.classes_list, name='classes_list'),
    path('api/classes/search/', views.api_class_search, name='api_class_search'),
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('teachers/new/', views.teacher_create, name='teacher_create'),
    path('teachers/<int:pk>/edit/', views.teacher_edit, name='teacher_edit'),
    path('teachers/<int:pk>/contract/', views.teacher_contract, name='teacher_contract'),
    path('teachers/<int:pk>/delete/', views.teacher_delete, name='teacher_delete'),
    path('teachers/<int:pk>/plan/upload/', views.teacher_plan_upload, name='teacher_plan_upload'),
    path('teachers/<int:pk>/plan/download/', views.teacher_plan_download, name='teacher_plan_download'),
    path('teachers/behavior/add/', views.teacher_behavior_add, name='teacher_behavior_add'),
    path('teachers/behavior/<int:pk>/update/', views.teacher_behavior_update, name='teacher_behavior_update'),
    path('teachers/behavior/<int:pk>/delete/', views.teacher_behavior_delete, name='teacher_behavior_delete'),
    path('teachers/<int:pk>/appreciation/', views.teacher_appreciation_print, name='teacher_appreciation_print'),
    path('subjects/new/', views.subject_create, name='subject_create'),
    path('subjects/<int:pk>/edit/', views.subject_edit, name='subject_edit'),
    path('subjects/<int:pk>/delete/', views.subject_delete, name='subject_delete'),
    path('subjects/', views.subject_list, name='subject_list'),
    path('grades/new/', views.grade_entry, name='grade_entry'),
    path('students/<int:pk>/exam-results/', views.student_exam_results, name='student_exam_results'),
]
